// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWU_EQ1Dja9diuPCW41rAC8_5V6ilPJfg',
    appId: '1:294989014319:web:1c0f3818836468ee99edda',
    messagingSenderId: '294989014319',
    projectId: 'juego-6bb25',
    authDomain: 'juego-6bb25.firebaseapp.com',
    databaseURL: 'https://juego-6bb25-default-rtdb.firebaseio.com',
    storageBucket: 'juego-6bb25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_5FYvJ7DSYmWsT7T9OszrJxiX7Hc5C4',
    appId: '1:294989014319:android:dec26702089d64d899edda',
    messagingSenderId: '294989014319',
    projectId: 'juego-6bb25',
    databaseURL: 'https://juego-6bb25-default-rtdb.firebaseio.com',
    storageBucket: 'juego-6bb25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbjIyjfJD3_289xI--5zb5xULVerFqTk',
    appId: '1:294989014319:ios:53c298a510890ca799edda',
    messagingSenderId: '294989014319',
    projectId: 'juego-6bb25',
    databaseURL: 'https://juego-6bb25-default-rtdb.firebaseio.com',
    storageBucket: 'juego-6bb25.appspot.com',
    iosBundleId: 'com.example.prueba3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVbjIyjfJD3_289xI--5zb5xULVerFqTk',
    appId: '1:294989014319:ios:53c298a510890ca799edda',
    messagingSenderId: '294989014319',
    projectId: 'juego-6bb25',
    databaseURL: 'https://juego-6bb25-default-rtdb.firebaseio.com',
    storageBucket: 'juego-6bb25.appspot.com',
    iosBundleId: 'com.example.prueba3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWU_EQ1Dja9diuPCW41rAC8_5V6ilPJfg',
    appId: '1:294989014319:web:2be6b8643137a12699edda',
    messagingSenderId: '294989014319',
    projectId: 'juego-6bb25',
    authDomain: 'juego-6bb25.firebaseapp.com',
    databaseURL: 'https://juego-6bb25-default-rtdb.firebaseio.com',
    storageBucket: 'juego-6bb25.appspot.com',
  );

}